_BASE_: Base-YouTubeVIS-VideoInstanceSegmentation.yaml
MODEL:
  WEIGHTS: 'model_final_3c8ec9.pkl'
  META_ARCHITECTURE: 'VISAGE'
  SEM_SEG_HEAD:
    NAME: 'MaskFormerHead'
    IGNORE_VALUE: 255
    NUM_CLASSES: 40
    LOSS_WEIGHT: 1.0
    CONVS_DIM: 256
    MASK_DIM: 256
    NORM: 'GN'
    # pixel decoder
    PIXEL_DECODER_NAME: 'MSDeformAttnPixelDecoder'
    IN_FEATURES: ['res2', 'res3', 'res4', 'res5']
    DEFORMABLE_TRANSFORMER_ENCODER_IN_FEATURES: ['res3', 'res4', 'res5']
    COMMON_STRIDE: 4
    TRANSFORMER_ENC_LAYERS: 6
  MASK_FORMER:
    TRANSFORMER_DECODER_NAME: 'IncrementalVisageMultiScaleMaskedTransformerDecoder'
    TRANSFORMER_IN_FEATURE: 'multi_scale_pixel_decoder'
    DEEP_SUPERVISION: True
    NO_OBJECT_WEIGHT: 0.1
    CLASS_WEIGHT: 2.0
    MASK_WEIGHT: 5.0
    DICE_WEIGHT: 5.0
    HIDDEN_DIM: 256
    NUM_OBJECT_QUERIES: 100
    NHEADS: 8
    DROPOUT: 0.0
    DIM_FEEDFORWARD: 2048
    ENC_LAYERS: 0
    PRE_NORM: False
    ENFORCE_INPUT_PROJ: False
    SIZE_DIVISIBILITY: 32
    DEC_LAYERS: 10 # 9 decoder layers, add one for the loss on learnable query
    TRAIN_NUM_POINTS: 12544
    OVERSAMPLE_RATIO: 3.0
    IMPORTANCE_SAMPLE_RATIO: 0.75
    TEST:
      SEMANTIC_ON: False
      INSTANCE_ON: True
      PANOPTIC_ON: False
      OVERLAP_THRESHOLD: 0.8
      OBJECT_MASK_THRESHOLD: 0.8
DATASETS:
  DATASET_RATIO: [1.0, 0.75] # [1.0, 0.75]
  TRAIN: ("coco2ytvis2019_train", "ytvis_2019_train",) # () # 
  TEST: ("ytvis_2019_val",)
SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.0001
  CHECKPOINT_PERIOD: 2000
  STEPS: (15000,) # (15000,) # (15000,)
  MAX_ITER: 20000 # 20000 # 20000
INPUT:
  SAMPLING_FRAME_RANGE: 10
  SAMPLING_FRAME_NUM: 4
  MIN_SIZE_TRAIN_SAMPLING: 'choice_by_clip'
  RANDOM_FLIP: 'flip_by_clip'
  AUGMENTATIONS: []
  MIN_SIZE_TRAIN: (320, 352, 392, 416, 448, 480, 512, 544, 576, 608, 640)
  MAX_SIZE_TRAIN: 768
  MIN_SIZE_TEST: 480
  CROP:
    ENABLED: True
    TYPE: 'absolute_range'
    SIZE: (384, 600)
  PSEUDO:
    AUGMENTATIONS: ['rotation']
    MIN_SIZE_TRAIN: (320, 352, 392, 416, 448, 480, 512, 544, 576, 608, 640)
    MAX_SIZE_TRAIN: 768
    CROP:
      ENABLED: True
      TYPE: 'absolute_range'
      SIZE: (384, 600)
    COPY_PASTE: False
  FORMAT: 'RGB'
TEST:
  EVAL_PERIOD: 20000
CONTINUE:
  ENABLED: True
  INIT_METHOD: 'mib'
  # BASE_CLASSES: 20
  # NEW_CLASSES_STEP: 5
  # TASK: 1
CONT:
  BASE_CLS: 20
  INC_CLS: 5
  TASK: 1 # change task step
  MODEL_OLD_WEIGHT: "./output/ytvis2019_VISAGE_1_8_2/step_0/model_0015999.pth" # para of old model
  BASE_NUM_QUERIES: 100
  INC_NUM_QUERIES: 25
  DIST:
    PSEUDO: False
    UKD: True
    KD_REW: True
    # CONTINUAL_LOSS_WEIGHT: (1., 5.,)
    KD_WEIGHT: 1.0  # class distillation loss weight
    MASK_KD: 5.0  # mask distillation loss weight
    POD_WEIGHT: 0.0
    ALPHA: 1.0
    UCE: False
    L2: False
    KD_DEEP: False
    USE_NEW: False
    EOS_POW: 0.0
    CE_NEW: False
    PSEUDO_TYPE: 0
    IOU_THRESHOLD: 0.5
    PSEUDO_THRESHOLD: 0.0
    
    



